ALTER TABLE fraud_articles
ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0);

ALTER TABLE fraud_articles
ADD COLUMN IF NOT EXISTS failed_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS ingestion_runs (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ran_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	source_newsapi INTEGER NOT NULL DEFAULT 0,
	source_rss INTEGER NOT NULL DEFAULT 0,
	source_scraped INTEGER NOT NULL DEFAULT 0,
	total_fetched INTEGER NOT NULL DEFAULT 0,
	duplicates INTEGER NOT NULL DEFAULT 0,
	inserted INTEGER NOT NULL DEFAULT 0,
	errors INTEGER NOT NULL DEFAULT 0,
	target_met BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS classification_runs (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ran_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	total_considered INTEGER NOT NULL DEFAULT 0,
	classified INTEGER NOT NULL DEFAULT 0,
	retried INTEGER NOT NULL DEFAULT 0,
	failed INTEGER NOT NULL DEFAULT 0,
	auto_approved INTEGER NOT NULL DEFAULT 0,
	needs_review INTEGER NOT NULL DEFAULT 0,
	used_ai INTEGER NOT NULL DEFAULT 0,
	used_heuristic INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_ingestion_runs_ran_at ON ingestion_runs (ran_at DESC);
CREATE INDEX IF NOT EXISTS idx_classification_runs_ran_at ON classification_runs (ran_at DESC);
